name: proximity_client
description: Proximity mobile app for users.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  proximity:
    path: ../
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.0.3
  url_launcher: ^6.1.4
  http: ^1.2.1
  dio: ^5.4.2+1
  google_maps_flutter: ^2.1.8
  image_picker: ^1.0.7
  shimmer: ^3.0.0
  hive: ^2.0.4
  
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  onesignal_flutter: ^5.1.4
  pay: ^2.0.0
  mask_text_input_formatter: ^2.4.0
  flutter_credit_card: ^4.0.1
  geolocator: ^11.0.0
  flutter_deep_linking : ^0.2.1
  uni_links: ^0.5.0
  google_sign_in: ^6.2.1
  multi_select_flutter: ^4.1.3
  
  

  geocoding: any
  intl_phone_field: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  hive_generator: ^2.0.1
  build_runner: ^2.1.11
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  image: assets/proximity-logo-light.png
  image_dark: assets/proximity-logo-dark.png
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/proximity-logo-light.png
    - assets/proximity-logo-dark.png
    - assets/img/ar.png
    - assets/img/fr.png
    - assets/img/en.png
    - assets/img/illustration-1.png
    - assets/img/illustration-2.png
    - assets/img/illustration-3.png
    - assets/img/facebook.png
    - assets/img/google.png
    - assets/img/twitter.png
    - assets/img/products/product-1.png
    - assets/img/products/product-2.png
    - assets/img/products/product-3.png
    - assets/img/products/product-4.png
    - assets/img/products/product-5.png
    - assets/img/products/product-6.png
    - assets/img/products/product-7.png
    - assets/img/products/product-8.png
    - assets/img/products/product-9.png
    - assets/img/products/product-10.png
    - assets/img/products/product-11.png
    - assets/img/ads/ad_1.png
    - assets/img/ads/ad_2.png
    - assets/img/ads/ad_3.png
    - assets/img/ads/ad_4.png
    - assets/img/ads/ad_5.png
    - assets/img/welcome.png
    - assets/apple-pay.png
    - assets/google-pay.png
    - assets/img/return_icon.png
    - assets/img/return_icon2.png
    - assets/img/refund_icon.png
    - assets/img/refund_icon2.png
